id = "ez"
name = "EZ"
version = "0.1.0"
schema_version = 1
description = "Syntax highlighting for the EZ programming language"
repository = "https://github.com/SchoolyB/EZ"
authors = ["Marshall Burns"]
themes = []
icon_themes = []
languages = ["languages/ez"]
capabilities = []

[grammars.ez]
repository = "https://github.com/SchoolyB/tree-sitter-ez"
rev = "888941bbccbc0fb6d14b43120416348d38584302"
