id = "ez"
name = "EZ"
version = "0.2.0"
schema_version = 1
description = "Syntax highlighting and language server for the EZ programming language"
repository = "https://github.com/SchoolyB/EZ"
authors = ["Marshall Burns"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.ez]
repository = "https://github.com/SchoolyB/tree-sitter-ez"
rev = "ec039f5e63095fe4759c0463a4fa34f6374f8a7a"

[language_servers.ez-lsp]
language = "EZ"
